language: php
php:
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

install: composer install
before_script:
  - cp vendor/clearbooks/labs-php-client-mysql/config/db-config.sample.php vendor/clearbooks/labs-php-client-mysql/config/db-config.php
  - mysql -e 'create database labs; SET GLOBAL sql_mode = "";'
script:
  - cat vendor/clearbooks/labs-schema/sql/*.sql | mysql -uroot labs
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
