language: php
php:
  - 7.0

install: composer install --dev --verbose
before_script:
  - cp vendor/clearbooks/labs-php-client-mysql/config/db-config.sample.php vendor/clearbooks/labs-php-client-mysql/config/db-config.php
  - mysql -e 'create database labs;'
script:
  - cat vendor/clearbooks/labs-schema/sql/*.sql | mysql -uroot labs
  - vendor/phpunit/phpunit/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml
